FROM node:10.20
LABEL maintainer Viccsen<252704620@qq.com>
RUN mkdir -p /h5
WORKDIR /h5
COPY . /h5
RUN npm config set registry https://registry.taobao.org && npm i

EXPOSE 8080
CMD [ "npm", "start" ]
