FROM node:10.20.1-slim
LABEL maintainer Viccsen<252704620@qq.com>
RUN mkdir -p /h5
WORKDIR /h5
COPY . /h5
RUN npm install --registry=https://registry.npm.taobao.org

EXPOSE 8080
CMD [ "npm", "start" ]
